export const completeProducts = [
  // === 瓦斯爐類 (15個) ===
  {
    name: '雙口瓦斯爐 玻璃面板',
    description: '黑色鋼化玻璃面板，安全熄火裝置，火力調節精準，適合小家庭',
    price: 5600,
    stock: 15,
    categoryId: 'gas-stoves',
    featured: true,
    sortOrder: 1,
    filename: 'gas-stove-2-burner.png',
    prompt: 'Professional two-burner gas stove with black glass panel, modern kitchen appliance, white background, high quality product photography'
  },
  {
    name: '三口瓦斯爐 不鏽鋼',
    description: '304不鏽鋼面板，耐用易清潔，火力強勁，專業級品質',
    price: 7000,
    stock: 10,
    categoryId: 'gas-stoves',
    featured: true,
    sortOrder: 2,
    filename: 'gas-stove-3-burner.png',
    prompt: 'Three-burner gas stove with stainless steel surface, modern kitchen appliance, white background, professional product photography'
  },
  {
    name: '四口瓦斯爐 專業款',
    description: '適合家庭聚餐，大火力設計，安全可靠，商用級性能',
    price: 8400,
    stock: 8,
    categoryId: 'gas-stoves',
    featured: false,
    sortOrder: 3,
    filename: 'gas-stove-4-burner.png',
    prompt: 'Four-burner professional gas stove, commercial kitchen appliance, white background, high quality product photography'
  },
  {
    name: '單口瓦斯爐 小型',
    description: '適合小家庭使用，節省空間，便於移動',
    price: 3600,
    stock: 20,
    categoryId: 'gas-stoves',
    featured: false,
    sortOrder: 4,
    filename: 'gas-stove-1-burner.png',
    prompt: 'Compact single-burner gas stove, small kitchen appliance, white background, product photography'
  },
  {
    name: '不鏽鋼雙口瓦斯爐',
    description: '高品質不鏽鋼材質，耐用防鏽，火力調節精準',
    price: 4800,
    stock: 12,
    categoryId: 'gas-stoves',
    featured: false,
    sortOrder: 5,
    filename: 'gas-stove-ss-2-burner.png',
    prompt: 'High quality stainless steel two-burner gas stove, modern kitchen appliance, white background, professional product photography'
  },
  {
    name: '嵌入式三口瓦斯爐',
    description: '嵌入式設計節省空間，黑色陶瓷面板，安全熄火',
    price: 7600,
    stock: 8,
    categoryId: 'gas-stoves',
    featured: true,
    sortOrder: 6,
    filename: 'gas-stove-built-in.png',
    prompt: 'Built-in three-burner gas stove with black ceramic glass surface, modern kitchen appliance, white background, product photography'
  },
  {
    name: '陶瓷面板雙口爐',
    description: '白色陶瓷面板，易清潔，防刮花，現代設計',
    price: 5200,
    stock: 15,
    categoryId: 'gas-stoves',
    featured: false,
    sortOrder: 7,
    filename: 'gas-stove-ceramic.png',
    prompt: 'Two-burner gas stove with white ceramic glass panel, modern kitchen appliance, white background, product photography'
  },
  {
    name: '商用五口瓦斯爐',
    description: '專業廚房用，五個爐頭，大火力，耐高溫',
    price: 11600,
    stock: 5,
    categoryId: 'gas-stoves',
    featured: false,
    sortOrder: 8,
    filename: 'gas-stove-commercial.png',
    prompt: 'Commercial five-burner gas stove, professional kitchen equipment, stainless steel, white background, product photography'
  },
  {
    name: '桌面式單口瓦斯爐',
    description: '桌面型設計，適合小空間，易於移動',
    price: 2400,
    stock: 20,
    categoryId: 'gas-stoves',
    featured: false,
    sortOrder: 9,
    filename: 'gas-stove-desktop.png',
    prompt: 'Desktop single burner portable gas stove, compact design, white background, product photography'
  },
  {
    name: '智能觸控瓦斯爐',
    description: '智能觸控面板，定時關火，安全防護，現代化設計',
    price: 9800,
    stock: 10,
    categoryId: 'gas-stoves',
    featured: true,
    sortOrder: 10,
    filename: 'gas-stove-smart.png',
    prompt: 'Smart touch control gas stove with digital display, modern kitchen appliance, white background, product photography'
  },
  {
    name: '雙面火瓦斯爐',
    description: '雙面同時加熱，火力可調，高效節能',
    price: 8200,
    stock: 8,
    categoryId: 'gas-stoves',
    featured: false,
    sortOrder: 11,
    filename: 'gas-stove-double-side.png',
    prompt: 'Double-sided gas stove with burners on both sides, commercial kitchen equipment, white background, product photography'
  },
  {
    name: '紅外線瓦斯爐',
    description: '紅外線感應加熱，高效節能，安全無明火',
    price: 6400,
    stock: 12,
    categoryId: 'gas-stoves',
    featured: false,
    sortOrder: 12,
    filename: 'gas-stove-infrared.png',
    prompt: 'Infrared gas stove with ceramic burners, modern kitchen appliance, white background, product photography'
  },
  {
    name: '防爆瓦斯爐',
    description: '防爆安全設計，工業級品質，適合商用',
    price: 12800,
    stock: 5,
    categoryId: 'gas-stoves',
    featured: false,
    sortOrder: 13,
    filename: 'gas-stove-explosion-proof.png',
    prompt: 'Explosion-proof industrial gas stove, heavy duty stainless steel, white background, product photography'
  },
  {
    name: '簡易雙口瓦斯爐',
    description: '簡單實用設計，經濟實惠，適合出租屋',
    price: 2800,
    stock: 25,
    categoryId: 'gas-stoves',
    featured: false,
    sortOrder: 14,
    filename: 'gas-stove-simple.png',
    prompt: 'Simple two-burner gas stove, basic design, affordable kitchen appliance, white background, product photography'
  },
  {
    name: '豪華五口瓦斯爐',
    description: '豪華外觀設計，五個爐頭，觸控面板，高端品質',
    price: 15800,
    stock: 6,
    categoryId: 'gas-stoves',
    featured: true,
    sortOrder: 15,
    filename: 'gas-stove-luxury.png',
    prompt: 'Luxury five-burner gas stove with premium finish, touch control, white background, product photography'
  },

  // === 熱水器類 (15個) ===
  {
    name: '即熱式電熱水器',
    description: '即開即熱，省電環保，安全過熱保護',
    price: 7000,
    stock: 12,
    categoryId: 'water-heaters',
    featured: true,
    sortOrder: 1,
    filename: 'water-heater-instant.png',
    prompt: 'Instant electric water heater, wall-mounted, modern white appliance, white background, product photography'
  },
  {
    name: '儲水式電熱水器 40L',
    description: '40公升容量，適合2-3人使用',
    price: 9000,
    stock: 10,
    categoryId: 'water-heaters',
    featured: true,
    sortOrder: 2,
    filename: 'water-heater-storage.png',
    prompt: '40L storage electric water heater, cylindrical tank, white appliance, white background, product photography'
  },
  {
    name: '瓦斯熱水器 8L',
    description: '8公升大水量，全家共用無壓力',
    price: 10400,
    stock: 8,
    categoryId: 'water-heaters',
    featured: false,
    sortOrder: 3,
    filename: 'water-heater-gas-8l.png',
    prompt: '8L gas water heater, compact wall-mounted unit, modern appliance, white background, product photography'
  },
  {
    name: '瓦斯熱水器 10L',
    description: '10公升超大水量，適合大家庭',
    price: 13000,
    stock: 6,
    categoryId: 'water-heaters',
    featured: false,
    sortOrder: 4,
    filename: 'water-heater-gas-10l.png',
    prompt: '10L gas water heater, larger capacity unit, modern appliance, white background, product photography'
  },
  {
    name: '即熱式電熱水器 6L',
    description: '小型即熱式，適合單人使用，省電省水',
    price: 5600,
    stock: 18,
    categoryId: 'water-heaters',
    featured: false,
    sortOrder: 5,
    filename: 'water-heater-instant-6l.png',
    prompt: 'Compact 6L instant electric water heater, wall-mounted, white appliance, white background, product photography'
  },
  {
    name: '儲水式電熱水器 20L',
    description: '20公升容量，適合小家庭，保溫效果佳',
    price: 7600,
    stock: 14,
    categoryId: 'water-heaters',
    featured: false,
    sortOrder: 6,
    filename: 'water-heater-storage-20l.png',
    prompt: '20L storage electric water heater, compact tank, white appliance, white background, product photography'
  },
  {
    name: '儲水式電熱水器 60L',
    description: '60公升大容量，大家庭首選，快速加熱',
    price: 13600,
    stock: 6,
    categoryId: 'water-heaters',
    featured: true,
    sortOrder: 7,
    filename: 'water-heater-storage-60l.png',
    prompt: '60L large capacity storage electric water heater, tall cylindrical tank, white appliance, white background, product photography'
  },
  {
    name: '太陽能熱水器系統',
    description: '環保節能，利用太陽能加熱，搭配電輔助',
    price: 30000,
    stock: 3,
    categoryId: 'water-heaters',
    featured: true,
    sortOrder: 8,
    filename: 'solar-water-heater.png',
    prompt: 'Solar water heater system with panels and storage tank, eco-friendly energy system, white background, product photography'
  },
  {
    name: '熱泵熱水器',
    description: '空氣能熱泵技術，高效節能，全年適用',
    price: 24000,
    stock: 5,
    categoryId: 'water-heaters',
    featured: false,
    sortOrder: 9,
    filename: 'heat-pump-water-heater.png',
    prompt: 'Heat pump water heater, energy efficient system, white appliance, white background, product photography'
  },
  {
    name: '智能電熱水器',
    description: 'WiFi智能控制，APP遠端操作，定時預約',
    price: 11000,
    stock: 8,
    categoryId: 'water-heaters',
    featured: true,
    sortOrder: 10,
    filename: 'smart-water-heater.png',
    prompt: 'Smart electric water heater with WiFi control, digital display, white appliance, white background, product photography'
  },
  {
    name: '快熱式燃氣熱水器',
    description: '即熱即出，無需儲水，節省空間',
    price: 8800,
    stock: 10,
    categoryId: 'water-heaters',
    featured: false,
    sortOrder: 11,
    filename: 'instant-gas-water-heater.png',
    prompt: 'Instant gas water heater, tankless system, wall-mounted unit, white background, product photography'
  },
  {
    name: '小戶型熱水器',
    description: '小巧設計，適合公寓或套房，省空間',
    price: 6200,
    stock: 15,
    categoryId: 'water-heaters',
    featured: false,
    sortOrder: 12,
    filename: 'compact-water-heater.png',
    prompt: 'Compact small apartment water heater, space-saving design, white appliance, white background, product photography'
  },
  {
    name: '商用熱水器',
    description: '大流量商用級，適合餐廳或旅館，連續供水',
    price: 18000,
    stock: 4,
    categoryId: 'water-heaters',
    featured: false,
    sortOrder: 13,
    filename: 'commercial-water-heater.png',
    prompt: 'Commercial large capacity water heater for business use, industrial design, white background, product photography'
  },
  {
    name: '恆溫熱水器',
    description: '精準恆溫控制，舒適洗浴，安全可靠',
    price: 9800,
    stock: 12,
    categoryId: 'water-heaters',
    featured: false,
    sortOrder: 14,
    filename: 'constant-temp-water-heater.png',
    prompt: 'Constant temperature water heater with digital thermostat control, white appliance, white background, product photography'
  },
  {
    name: '速熱熱水器',
    description: '3秒速熱技術，快速升溫，節省時間',
    price: 7800,
    stock: 14,
    categoryId: 'water-heaters',
    featured: false,
    sortOrder: 15,
    filename: 'quick-heat-water-heater.png',
    prompt: 'Quick heating water heater with rapid temperature rise technology, white appliance, white background, product photography'
  },

  // === 瓦斯桶類 (10個) ===
  {
    name: '瓦斯桶 20KG',
    description: '標準20公斤瓦斯桶，容量充足，家庭首選',
    price: 1900,
    stock: 50,
    categoryId: 'gas-cylinders',
    featured: true,
    sortOrder: 1,
    filename: 'gas-cylinder-20kg.png',
    prompt: '20KG standard gas cylinder, red colored metal tank, professional product photography, white background'
  },
  {
    name: '瓦斯桶 16KG',
    description: '16公斤瓦斯桶，小家庭首選',
    price: 1500,
    stock: 40,
    categoryId: 'gas-cylinders',
    featured: false,
    sortOrder: 2,
    filename: 'gas-cylinder-16kg.png',
    prompt: '16KG gas cylinder, red colored metal tank, medium size, white background, product photography'
  },
  {
    name: '瓦斯桶 12KG',
    description: '12公斤瓦斯桶，適合公寓',
    price: 1200,
    stock: 30,
    categoryId: 'gas-cylinders',
    featured: false,
    sortOrder: 3,
    filename: 'gas-cylinder-12kg.png',
    prompt: '12KG gas cylinder, red colored metal tank, smaller size, white background, product photography'
  },
  {
    name: '瓦斯桶 8KG',
    description: '8公斤瓦斯桶，輕巧方便',
    price: 900,
    stock: 25,
    categoryId: 'gas-cylinders',
    featured: false,
    sortOrder: 4,
    filename: 'gas-cylinder-8kg.png',
    prompt: '8KG compact gas cylinder, red colored metal tank, small size, white background, product photography'
  },
  {
    name: '瓦斯桶 5KG',
    description: '5公斤小桶，輕便易攜，適合露營',
    price: 700,
    stock: 40,
    categoryId: 'gas-cylinders',
    featured: false,
    sortOrder: 5,
    filename: 'gas-cylinder-5kg.png',
    prompt: '5KG small portable gas cylinder, red colored metal tank, compact size, white background, product photography'
  },
  {
    name: '工業用瓦斯桶 50KG',
    description: '50公斤大桶，工業用量，經濟實惠',
    price: 4400,
    stock: 10,
    categoryId: 'gas-cylinders',
    featured: false,
    sortOrder: 6,
    filename: 'gas-cylinder-50kg.png',
    prompt: '50KG industrial gas cylinder, large red metal tank, commercial grade, white background, product photography'
  },
  {
    name: '鋁瓶瓦斯桶 10KG',
    description: '鋁合金材質，輕量設計，更易搬運',
    price: 2400,
    stock: 20,
    categoryId: 'gas-cylinders',
    featured: true,
    sortOrder: 7,
    filename: 'aluminum-gas-cylinder.png',
    prompt: '10KG aluminum alloy gas cylinder, lightweight design, silver metal tank, white background, product photography'
  },
  {
    name: '複合材質瓦斯桶',
    description: '玻璃纖維複合材料，抗腐蝕，超輕量化',
    price: 2800,
    stock: 15,
    categoryId: 'gas-cylinders',
    featured: false,
    sortOrder: 8,
    filename: 'composite-gas-cylinder.png',
    prompt: 'Composite material gas cylinder, fiberglass construction, lightweight design, white background, product photography'
  },
  {
    name: '迷你瓦斯罐 2KG',
    description: '2公斤迷你罐，戶外露營必備',
    price: 350,
    stock: 60,
    categoryId: 'gas-cylinders',
    featured: false,
    sortOrder: 9,
    filename: 'mini-gas-canister.png',
    prompt: '2KG mini gas canister, portable camping gas, small red tank, white background, product photography'
  },
  {
    name: '專業級瓦斯桶 15KG',
    description: '工業級品質，安全閥門，耐用可靠',
    price: 3200,
    stock: 25,
    categoryId: 'gas-cylinders',
    featured: false,
    sortOrder: 10,
    filename: 'pro-gas-cylinder.png',
    prompt: 'Professional grade 15KG gas cylinder with safety valve, red metal tank, white background, product photography'
  },

  // === 烹調用品類 (12個) ===
  {
    name: '瓦斯壓力鍋',
    description: '快速烹調，省時省氣，多層安全裝置',
    price: 1960,
    stock: 25,
    categoryId: 'cooking',
    featured: false,
    sortOrder: 1,
    filename: 'gas-pressure-cooker.png',
    prompt: 'Gas pressure cooker, stainless steel pot with locking lid, cooking appliance, white background, product photography'
  },
  {
    name: '瓦斯蒸鍋',
    description: '多層蒸籠設計，健康烹調方式',
    price: 1300,
    stock: 20,
    categoryId: 'cooking',
    featured: false,
    sortOrder: 2,
    filename: 'gas-steamer.png',
    prompt: 'Gas steamer pot with multiple tiers, stainless steel cooking appliance, white background, product photography'
  },
  {
    name: '瓦斯煎鍋',
    description: '平底設計，導熱快速，不沾塗層',
    price: 900,
    stock: 30,
    categoryId: 'cooking',
    featured: false,
    sortOrder: 3,
    filename: 'gas-frying-pan.png',
    prompt: 'Gas compatible frying pan with non-stick coating, cookware, white background, product photography'
  },
  {
    name: '瓦斯烤爐',
    description: '戶外燒烤用，火力可調，便於清潔',
    price: 2400,
    stock: 15,
    categoryId: 'cooking',
    featured: true,
    sortOrder: 4,
    filename: 'gas-grill.png',
    prompt: 'Portable gas grill for outdoor cooking, camping equipment, white background, product photography'
  },
  {
    name: '瓦斯火鍋爐',
    description: '專業火鍋用，火力穩定，適合聚餐',
    price: 1160,
    stock: 35,
    categoryId: 'cooking',
    featured: false,
    sortOrder: 5,
    filename: 'gas-hotpot.png',
    prompt: 'Gas hot pot burner, portable heating element for hot pot dining, white background, product photography'
  },
  {
    name: '中式炒鍋',
    description: '中式炒鍋設計，適合猛火爆炒，不鏽鋼材質',
    price: 880,
    stock: 28,
    categoryId: 'cooking',
    featured: false,
    sortOrder: 6,
    filename: 'chinese-wok.png',
    prompt: 'Chinese wok pan for stir frying, carbon steel, traditional cooking vessel, white background, product photography'
  },
  {
    name: '不鏽鋼湯鍋',
    description: '304不鏽鋼，耐酸鹼，適合煲湯',
    price: 720,
    stock: 35,
    categoryId: 'cooking',
    featured: false,
    sortOrder: 7,
    filename: 'stainless-soup-pot.png',
    prompt: 'Stainless steel soup pot, 304 grade, durable cooking vessel, white background, product photography'
  },
  {
    name: '雙耳炒鍋',
    description: '雙耳設計，便於握持，專業廚師推薦',
    price: 960,
    stock: 22,
    categoryId: 'cooking',
    featured: false,
    sortOrder: 8,
    filename: 'double-handle-wok.png',
    prompt: 'Double handle wok pan, professional chef design, carbon steel, white background, product photography'
  },
  {
    name: '鑄鐵煎鍋',
    description: '鑄鐵材質，保溫效果佳，適合煎肉',
    price: 1080,
    stock: 18,
    categoryId: 'cooking',
    featured: false,
    sortOrder: 9,
    filename: 'cast-iron-pan.png',
    prompt: 'Cast iron frying pan, excellent heat retention, cooking vessel, white background, product photography'
  },
  {
    name: '不沾炒鍋',
    description: '特氟龍塗層，不沾易清潔，少油健康烹調',
    price: 640,
    stock: 40,
    categoryId: 'cooking',
    featured: false,
    sortOrder: 10,
    filename: 'non-stick-wok.png',
    prompt: 'Non-stick coated wok pan, Teflon coating, healthy cooking, white background, product photography'
  },
  {
    name: '燒烤爐架',
    description: '戶外燒烤爐架，可拆卸，便於收納',
    price: 1800,
    stock: 20,
    categoryId: 'cooking',
    featured: false,
    sortOrder: 11,
    filename: 'bbq-grill-rack.png',
    prompt: 'Outdoor BBQ grill rack, collapsible design, camping cooking equipment, white background, product photography'
  },
  {
    name: '多功能蒸鍋',
    description: '一鍋多用，可蒸可煮可燉，節省空間',
    price: 1440,
    stock: 15,
    categoryId: 'cooking',
    featured: false,
    sortOrder: 12,
    filename: 'multi-cooker.png',
    prompt: 'Multi-function cooking pot, steamer and cooker combination, stainless steel, white background, product photography'
  },

  // === 戶外用品類 (12個) ===
  {
    name: '戶外瓦斯爐',
    description: '露營專用，輕便設計，攜帶方便',
    price: 1780,
    stock: 22,
    categoryId: 'outdoor',
    featured: true,
    sortOrder: 1,
    filename: 'outdoor-gas-stove.png',
    prompt: 'Outdoor camping gas stove, portable folding design, camping equipment, white background, product photography'
  },
  {
    name: '戶外瓦斯燈',
    description: '露營照明，亮度可調，經久耐用',
    price: 900,
    stock: 28,
    categoryId: 'outdoor',
    featured: false,
    sortOrder: 2,
    filename: 'outdoor-gas-lamp.png',
    prompt: 'Outdoor gas camping lantern, portable lighting device, camping equipment, white background, product photography'
  },
  {
    name: '迷你便攜瓦斯爐',
    description: '超輕便設計，單人露營最佳選擇',
    price: 760,
    stock: 30,
    categoryId: 'outdoor',
    featured: false,
    sortOrder: 3,
    filename: 'mini-portable-stove.png',
    prompt: 'Mini portable single burner gas stove, ultralight camping gear, white background, product photography'
  },
  {
    name: '瓦斯暖爐',
    description: '冬季取暖，安全設計，熱效率高',
    price: 3600,
    stock: 12,
    categoryId: 'outdoor',
    featured: false,
    sortOrder: 4,
    filename: 'gas-heater.png',
    prompt: 'Portable gas heater, winter heating appliance, safety design, white background, product photography'
  },
  {
    name: '卡式瓦斯爐',
    description: '使用卡式瓦斯罐，便於更換，戶外必備',
    price: 680,
    stock: 45,
    categoryId: 'outdoor',
    featured: false,
    sortOrder: 5,
    filename: 'cartridge-stove.png',
    prompt: 'Cartridge gas stove for camping, uses portable gas canisters, outdoor cooking equipment, white background, product photography'
  },
  {
    name: '戶外咖啡壺',
    description: '露營煮咖啡專用，快速加熱，輕便設計',
    price: 520,
    stock: 35,
    categoryId: 'outdoor',
    featured: false,
    sortOrder: 6,
    filename: 'camping-coffee-pot.png',
    prompt: 'Outdoor camping coffee pot, portable design, aluminum construction, white background, product photography'
  },
  {
    name: '露營用烤盤',
    description: '戶外燒烤盤，不沾塗層，易於清潔',
    price: 1440,
    stock: 20,
    categoryId: 'outdoor',
    featured: false,
    sortOrder: 7,
    filename: 'camping-grill-pan.png',
    prompt: 'Camping grill pan with non-stick coating, outdoor cooking equipment, white background, product photography'
  },
  {
    name: '瓦斯燈串燈',
    description: '露營裝飾燈，瓦斯供電，溫暖光線',
    price: 1100,
    stock: 25,
    categoryId: 'outdoor',
    featured: false,
    sortOrder: 8,
    filename: 'gas-string-lights.png',
    prompt: 'Gas powered string lights for camping, warm ambient lighting, outdoor decoration, white background, product photography'
  },
  {
    name: '便攜火盆',
    description: '露營火盆，可攜式，適合戶外聚會',
    price: 2200,
    stock: 15,
    categoryId: 'outdoor',
    featured: false,
    sortOrder: 9,
    filename: 'portable-fire-pit.png',
    prompt: 'Portable fire pit for camping, outdoor gathering, metal construction, white background, product photography'
  },
  {
    name: '露營炊具組',
    description: '全套炊具組，包含鍋碗瓢盆，一人份',
    price: 1680,
    stock: 20,
    categoryId: 'outdoor',
    featured: false,
    sortOrder: 10,
    filename: 'camping-cookset.png',
    prompt: 'Camping cookware set, complete kitchen equipment for one person, aluminum and steel, white background, product photography'
  },
  {
    name: '戶外保溫箱',
    description: '露營保溫箱，長效保溫，便於攜帶',
    price: 880,
    stock: 25,
    categoryId: 'outdoor',
    featured: false,
    sortOrder: 11,
    filename: 'camping-cooler.png',
    prompt: 'Camping cooler box, thermal insulation, portable design, white background, product photography'
  },
  {
    name: '露營炊具掛架',
    description: '露營炊具掛架，懸掛式設計，節省空間',
    price: 640,
    stock: 30,
    categoryId: 'outdoor',
    featured: false,
    sortOrder: 12,
    filename: 'camping-hanger.png',
    prompt: 'Camping cookware hanging rack, space-saving design, metal construction, white background, product photography'
  },

  // === 安全配件類 (12個) ===
  {
    name: '瓦斯偵測器',
    description: '智能偵測，聲光報警，電池供電',
    price: 900,
    stock: 25,
    categoryId: 'safety',
    featured: true,
    sortOrder: 1,
    filename: 'gas-detector.png',
    prompt: 'Gas leak detector device, safety alarm system, modern electronic device, white background, product photography'
  },
  {
    name: '瓦斯警報器',
    description: '高靈敏度感應，自動報警，LCD顯示',
    price: 1360,
    stock: 20,
    categoryId: 'safety',
    featured: false,
    sortOrder: 2,
    filename: 'gas-alarm.png',
    prompt: 'Gas alarm system with digital display, safety monitoring device, white background, product photography'
  },
  {
    name: '緊急瓦斯切斷閥',
    description: '自動切斷，機械式操作，無需電源',
    price: 700,
    stock: 35,
    categoryId: 'safety',
    featured: false,
    sortOrder: 3,
    filename: 'emergency-shut-off.png',
    prompt: 'Emergency gas shut-off valve, safety device, mechanical valve, white background, product photography'
  },
  {
    name: '瓦斯濾清器',
    description: '過濾雜質，延長設備壽命，提高燃燒效率',
    price: 560,
    stock: 40,
    categoryId: 'safety',
    featured: false,
    sortOrder: 4,
    filename: 'gas-filter.png',
    prompt: 'Gas filter cleaning device, pipeline accessory, metal construction, white background, product photography'
  },
  {
    name: '一氧化碳偵測器',
    description: '偵測一氧化碳，數位顯示，高分貝警報',
    price: 1280,
    stock: 22,
    categoryId: 'safety',
    featured: true,
    sortOrder: 5,
    filename: 'co-detector.png',
    prompt: 'Carbon monoxide detector with digital display, safety alarm device, white background, product photography'
  },
  {
    name: '瓦斯漏氣檢測液',
    description: '噴灑檢測，快速定位漏氣點，方便維修',
    price: 380,
    stock: 50,
    categoryId: 'safety',
    featured: false,
    sortOrder: 6,
    filename: 'gas-leak-spray.png',
    prompt: 'Gas leak detection spray, liquid for identifying leaks, maintenance tool, white background, product photography'
  },
  {
    name: '緊急呼吸面罩',
    description: '逃生用面罩，防毒防煙，家庭必備',
    price: 580,
    stock: 30,
    categoryId: 'safety',
    featured: false,
    sortOrder: 7,
    filename: 'emergency-mask.png',
    prompt: 'Emergency escape respirator mask, smoke protection device, safety equipment, white background, product photography'
  },
  {
    name: '消防滅火毯',
    description: '玻璃纖維滅火毯，隔絕火源，緊急滅火',
    price: 480,
    stock: 35,
    categoryId: 'safety',
    featured: false,
    sortOrder: 8,
    filename: 'fire-blanket.png',
    prompt: 'Fire extinguishing blanket, fiberglass material, emergency fire safety equipment, white background, product photography'
  },
  {
    name: '小型滅火器',
    description: '乾粉滅火器，家庭用，輕便易操作',
    price: 680,
    stock: 28,
    categoryId: 'safety',
    featured: false,
    sortOrder: 9,
    filename: 'small-fire-extinguisher.png',
    prompt: 'Small portable fire extinguisher, dry powder, home safety equipment, white background, product photography'
  },
  {
    name: '瓦斯表',
    description: '數位瓦斯表，精準計量，用量監控',
    price: 880,
    stock: 20,
    categoryId: 'safety',
    featured: false,
    sortOrder: 10,
    filename: 'gas-meter.png',
    prompt: 'Digital gas meter, accurate measurement, consumption monitoring device, white background, product photography'
  },
  {
    name: '煙霧警報器',
    description: '光電感煙，高分貝警報，電池供電',
    price: 720,
    stock: 25,
    categoryId: 'safety',
    featured: false,
    sortOrder: 11,
    filename: 'smoke-alarm.png',
    prompt: 'Photoelectric smoke alarm detector, high decibel warning, battery powered, white background, product photography'
  },
  {
    name: '緊急照明燈',
    description: '斷電自動亮燈，LED光源，長亮時間',
    price: 540,
    stock: 40,
    categoryId: 'safety',
    featured: false,
    sortOrder: 12,
    filename: 'emergency-light.png',
    prompt: 'Emergency backup light, automatic power outage activation, LED illumination, white background, product photography'
  },

  // === 管路配件類 (16個) ===
  {
    name: '瓦斯管 1公尺',
    description: '高品質瓦斯管，安全耐用',
    price: 360,
    stock: 100,
    categoryId: 'pipes',
    featured: true,
    sortOrder: 1,
    filename: 'gas-hose.png',
    prompt: '1 meter gas hose pipe, flexible tubing, white background, product photography'
  },
  {
    name: '瓦斯調壓器',
    description: '精密調壓，火力穩定',
    price: 500,
    stock: 80,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 2,
    filename: 'gas-regulator.png',
    prompt: 'Gas pressure regulator valve, metallic device, white background, product photography'
  },
  {
    name: '瓦斯開關',
    description: '安全開關，操作簡單',
    price: 240,
    stock: 120,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 3,
    filename: 'gas-valve.png',
    prompt: 'Gas stove control valve switch, metal knob, white background, product photography'
  },
  {
    name: '熱水器專用燃氣閥',
    description: '專用燃氣閥，安全可靠',
    price: 300,
    stock: 60,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 4,
    filename: 'water-heater-valve.png',
    prompt: 'Gas shut-off valve for water heater, brass colored, white background, product photography'
  },
  {
    name: '瓦斯三通接頭',
    description: 'T型接頭，一進兩出，黃銅材質',
    price: 300,
    stock: 50,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 5,
    filename: 'gas-t-fitting.png',
    prompt: 'Brass gas T-shaped fitting connector, plumbing accessory, white background, product photography'
  },
  {
    name: '瓦斯快速接頭',
    description: '快速連接，防脫落設計，操作便捷',
    price: 440,
    stock: 45,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 6,
    filename: 'gas-quick-connector.png',
    prompt: 'Gas quick connect coupling mechanism, easy connector device, white background, product photography'
  },
  {
    name: '瓦斯管夾',
    description: '固定管路，強度高，不鏽鋼材質',
    price: 160,
    stock: 60,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 7,
    filename: 'pipe-clamp.png',
    prompt: 'Gas pipe clamp fitting, stainless steel clamp, plumbing accessory, white background, product photography'
  },
  {
    name: '密封墊圈套裝',
    description: '多尺寸套裝，高質量橡膠，密封性佳',
    price: 240,
    stock: 55,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 8,
    filename: 'gasket-set.png',
    prompt: 'Set of gas sealing gaskets, rubber washers assortment, plumbing accessory, white background, product photography'
  },
  {
    name: 'L型瓦斯管接頭',
    description: '90度彎頭，安裝方便，黃銅製造',
    price: 320,
    stock: 50,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 9,
    filename: 'l-elbow-fitting.png',
    prompt: 'L-shaped gas pipe elbow fitting, 90 degree bend, brass construction, white background, product photography'
  },
  {
    name: '瓦斯管套管',
    description: '保護套管，防止磨損，延長壽命',
    price: 380,
    stock: 45,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 10,
    filename: 'pipe-sleeve.png',
    prompt: 'Gas pipe protective sleeve, prevents wear and tear, plastic tubing, white background, product photography'
  },
  {
    name: '高壓瓦斯管',
    description: '耐高壓設計，工業級品質，安全可靠',
    price: 480,
    stock: 40,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 11,
    filename: 'high-pressure-pipe.png',
    prompt: 'High pressure gas hose, reinforced construction, industrial grade, white background, product photography'
  },
  {
    name: '軟管接頭組',
    description: '軟管接頭套裝，多種規格，維修必備',
    price: 420,
    stock: 35,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 12,
    filename: 'hose-connector-set.png',
    prompt: 'Gas hose connector set assortment, multiple sizes, plumbing repair kit, white background, product photography'
  },
  {
    name: '四通瓦斯接頭',
    description: '四通設計，一分為四，黃銅材質',
    price: 380,
    stock: 30,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 13,
    filename: '4-way-fitting.png',
    prompt: 'Four-way gas pipe fitting, brass construction, plumbing accessory, white background, product photography'
  },
  {
    name: '螺紋接頭',
    description: '標準螺紋，通用型號，安裝簡便',
    price: 180,
    stock: 70,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 14,
    filename: 'threaded-fitting.png',
    prompt: 'Standard threaded gas pipe fitting, universal design, brass construction, white background, product photography'
  },
  {
    name: '管路固定座',
    description: '固定瓦斯管，穩固安裝，不鏽鋼',
    price: 220,
    stock: 55,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 15,
    filename: 'pipe-mounting-bracket.png',
    prompt: 'Gas pipe mounting bracket, secure installation, stainless steel, white background, product photography'
  },
  {
    name: '防爆閥門',
    description: '防爆閥門，自動復位，安全防護',
    price: 640,
    stock: 25,
    categoryId: 'pipes',
    featured: false,
    sortOrder: 16,
    filename: 'explosion-proof-valve.png',
    prompt: 'Explosion-proof safety valve, automatic reset, gas safety device, white background, product photography'
  },

  // === 維護工具類 (10個) ===
  {
    name: '爐具清潔劑',
    description: '專用清潔，去除油漬，不傷爐具',
    price: 360,
    stock: 40,
    categoryId: 'maintenance',
    featured: false,
    sortOrder: 1,
    filename: 'stove-cleaner.png',
    prompt: 'Stove cleaner spray bottle, cleaning product for gas appliances, white background, product photography'
  },
  {
    name: '瓦斯管清潔工具',
    description: '專用毛刷，深入清潔，操作簡單',
    price: 190,
    stock: 45,
    categoryId: 'maintenance',
    featured: false,
    sortOrder: 2,
    filename: 'pipe-cleaner.png',
    prompt: 'Gas pipe cleaning brush tool, maintenance equipment, white background, product photography'
  },
  {
    name: '維修工具包',
    description: '全套工具，包含扳手、鉗子等，家用必備',
    price: 760,
    stock: 20,
    categoryId: 'maintenance',
    featured: false,
    sortOrder: 3,
    filename: 'repair-toolkit.png',
    prompt: 'Gas appliance repair toolkit, wrenches and tools set, maintenance equipment, white background, product photography'
  },
  {
    name: '爐具腳座',
    description: '不鏽鋼腳座，穩固支撐，可調高度',
    price: 360,
    stock: 35,
    categoryId: 'maintenance',
    featured: false,
    sortOrder: 4,
    filename: 'stove-stand.png',
    prompt: 'Adjustable stainless steel stove stand legs, kitchen appliance support, white background, product photography'
  },
  {
    name: '風擋',
    description: '防風設計，提升燃燒效率，戶外必備',
    price: 500,
    stock: 30,
    categoryId: 'maintenance',
    featured: false,
    sortOrder: 5,
    filename: 'wind-shield.png',
    prompt: 'Gas stove wind shield, protective aluminum foil guard, camping accessory, white background, product photography'
  },
  {
    name: '點火器',
    description: '長柄設計，安全點火，瓦斯爐用',
    price: 240,
    stock: 40,
    categoryId: 'maintenance',
    featured: false,
    sortOrder: 6,
    filename: 'igniter.png',
    prompt: 'Gas stove piezoelectric igniter, long handle safety lighter, white background, product photography'
  },
  {
    name: '計時器',
    description: '廚房計時，提醒關火，烹調更安全',
    price: 560,
    stock: 32,
    categoryId: 'maintenance',
    featured: false,
    sortOrder: 7,
    filename: 'kitchen-timer.png',
    prompt: 'Digital kitchen timer device, cooking safety gadget, white background, product photography'
  },
  {
    name: '瓦斯檢測筆',
    description: '手持檢測，快速定位漏氣點，數位顯示',
    price: 680,
    stock: 25,
    categoryId: 'maintenance',
    featured: false,
    sortOrder: 8,
    filename: 'gas-leak-detector-pen.png',
    prompt: 'Handheld gas leak detector pen, digital display, portable testing device, white background, product photography'
  },
  {
    name: '管路扳手',
    description: '專用扳手，安裝拆卸，黃銅保護',
    price: 320,
    stock: 40,
    categoryId: 'maintenance',
    featured: false,
    sortOrder: 9,
    filename: 'pipe-wrench.png',
    prompt: 'Gas pipe专用 wrench, installation and removal tool, brass jaw protection, white background, product photography'
  },
  {
    name: '清潔刷組',
    description: '多種刷子，清潔爐具，細節到位',
    price: 280,
    stock: 35,
    categoryId: 'maintenance',
    featured: false,
    sortOrder: 10,
    filename: 'cleaning-brush-set.png',
    prompt: 'Cleaning brush set for gas appliances, multiple sizes, maintenance tool, white background, product photography'
  },

  // === 其他配件類 (18個) ===
  {
    name: '爐具腳墊',
    description: '防滑腳墊，保護桌面，減震降噪',
    price: 320,
    stock: 30,
    categoryId: 'other',
    featured: false,
    sortOrder: 1,
    filename: 'stove-foot-pad.png',
    prompt: 'Non-slip stove foot pads, table protection, vibration dampening, white background, product photography'
  },
  {
    name: '鋁箔紙',
    description: '食品級鋁箔，耐高溫，多用途',
    price: 120,
    stock: 100,
    categoryId: 'other',
    featured: false,
    sortOrder: 2,
    filename: 'aluminum-foil.png',
    prompt: 'Food grade aluminum foil roll, high temperature resistant, multipurpose kitchen supply, white background, product photography'
  },
  {
    name: '防火手套',
    description: '防燙手套，耐高溫，烹調必備',
    price: 280,
    stock: 40,
    categoryId: 'other',
    featured: false,
    sortOrder: 3,
    filename: 'heat-resistant-gloves.png',
    prompt: 'Heat resistant oven gloves, high temperature protection, cooking safety equipment, white background, product photography'
  },
  {
    name: '瓦斯爐蓋',
    description: '防塵蓋，保護爐具，保持清潔',
    price: 380,
    stock: 35,
    categoryId: 'other',
    featured: false,
    sortOrder: 4,
    filename: 'stove-cover.png',
    prompt: 'Gas stove protective cover, dust protection, keeps appliance clean, white background, product photography'
  },
  {
    name: '瓦斯罐支架',
    description: '固定瓦斯罐，穩固安全，可疊放',
    price: 260,
    stock: 45,
    categoryId: 'other',
    featured: false,
    sortOrder: 5,
    filename: 'gas-tank-stand.png',
    prompt: 'Gas cylinder storage stand rack, stable stacking design, metal construction, white background, product photography'
  },
  {
    name: '換氣扇',
    description: '廚房換氣，排氣除油，靜音設計',
    price: 880,
    stock: 25,
    categoryId: 'other',
    featured: false,
    sortOrder: 6,
    filename: 'range-hood.png',
    prompt: 'Kitchen range hood exhaust fan, oil removal, quiet operation, white background, product photography'
  },
  {
    name: '油網套裝',
    description: '可水洗油網，多件套裝，定期更換',
    price: 180,
    stock: 60,
    categoryId: 'other',
    featured: false,
    sortOrder: 7,
    filename: 'oil-filter-set.png',
    prompt: 'Washable oil filter mesh set, multiple pieces, replacement parts, white background, product photography'
  },
  {
    name: '廚房秤',
    description: '電子廚房秤，精準稱重，多單位',
    price: 420,
    stock: 30,
    categoryId: 'other',
    featured: false,
    sortOrder: 8,
    filename: 'kitchen-scale.png',
    prompt: 'Electronic kitchen scale, precise weighing, multiple units, white background, product photography'
  },
  {
    name: '溫度計',
    description: '食品溫度計，快速測溫，安全烹調',
    price: 180,
    stock: 40,
    categoryId: 'other',
    featured: false,
    sortOrder: 9,
    filename: 'food-thermometer.png',
    prompt: 'Food thermometer, quick temperature reading, safe cooking, white background, product photography'
  },
  {
    name: '廚房剪刀',
    description: '專用剪刀，不鏽鋼鋒利，多用途',
    price: 220,
    stock: 50,
    categoryId: 'other',
    featured: false,
    sortOrder: 10,
    filename: 'kitchen-scissors.png',
    prompt: 'Kitchen utility scissors, stainless steel sharp, multipurpose, white background, product photography'
  },
  {
    name: '置物架',
    description: '廚房置物架，省空間設計，多層',
    price: 680,
    stock: 20,
    categoryId: 'other',
    featured: false,
    sortOrder: 11,
    filename: 'storage-rack.png',
    prompt: 'Kitchen storage rack, space-saving design, multiple shelves, white background, product photography'
  },
  {
    name: '調味罐組',
    description: '調味罐套裝，密封設計，保持新鮮',
    price: 340,
    stock: 35,
    categoryId: 'other',
    featured: false,
    sortOrder: 12,
    filename: 'spice-jar-set.png',
    prompt: 'Spice jar storage set, sealed design, keeps fresh, white background, product photography'
  },
  {
    name: '量杯組',
    description: '多規格量杯，精準計量，透明設計',
    price: 260,
    stock: 40,
    categoryId: 'other',
    featured: false,
    sortOrder: 13,
    filename: 'measuring-cup-set.png',
    prompt: 'Measuring cup set with multiple sizes, accurate measurement, transparent design, white background, product photography'
  },
  {
    name: '保鮮盒組',
    description: '保鮮盒套裝，密閉設計，食物保存',
    price: 380,
    stock: 30,
    categoryId: 'other',
    featured: false,
    sortOrder: 14,
    filename: 'food-container-set.png',
    prompt: 'Food storage container set, sealed design, food preservation, white background, product photography'
  },
  {
    name: '瀝油勺',
    description: '不鏽鋼瀝油勺，細密濾網，耐用',
    price: 140,
    stock: 50,
    categoryId: 'other',
    featured: false,
    sortOrder: 15,
    filename: 'oil-skimmer.png',
    prompt: 'Stainless steel oil skimmer ladle, fine mesh strainer, durable, white background, product photography'
  },
  {
    name: '磨刀石',
    description: '雙面磨刀石，粗細兩用，刀具護養',
    price: 220,
    stock: 35,
    categoryId: 'other',
    featured: false,
    sortOrder: 16,
    filename: 'sharpening-stone.png',
    prompt: 'Double-sided sharpening stone, coarse and fine surfaces, knife maintenance, white background, product photography'
  },
  {
    name: '廚房抹布',
    description: '超細纖維抹布，吸水快，不掉毛',
    price: 160,
    stock: 80,
    categoryId: 'other',
    featured: false,
    sortOrder: 17,
    filename: 'kitchen-cloth.png',
    prompt: 'Microfiber kitchen cleaning cloths, highly absorbent, lint-free, white background, product photography'
  },
  {
    name: '防油圍裙',
    description: '防油防水圍裙，烹調保護，易於清潔',
    price: 320,
    stock: 25,
    categoryId: 'other',
    featured: false,
    sortOrder: 18,
    filename: 'oil-proof-apron.png',
    prompt: 'Oil-proof waterproof kitchen apron, cooking protection, easy to clean, white background, product photography'
  }
];
